#!/bin/sh
set -e

architecture_specific_packages=""
export DEBCONF_NOWARNINGS=yes
export DEBIAN_FRONTEND=noninteractive

echo "America/New_York" > /etc/timezone

apt-get update -y -q

if [ "$(apt-cache search --names-only '^postfix-pgsql$')" != "" ]; then
    architecture_specific_packages="${architecture_specific_packages} postfix-pgsql"
fi

apt-get install -y libsasl2-modules sasl2-bin
apt-get install -y postfix postfix-pcre postfix-ldap ${architecture_specific_packages}
apt-get install -y opendkim
libcurl="libcurl4"

if [ "$(apt-cache search --names-only '^libcurl4t64$')" != "" ]; then
    libcurl="libcurl4t64"
fi

apt-get install -y ca-certificates tzdata supervisor rsyslog bash opendkim-tools curl ${libcurl} libjsoncpp25 sasl2-bin postfix-lmdb procps logrotate cron net-tools colorized-logs netcat-openbsd ${RELEASE_SPECIFIC_PACKAGES}
apt-get clean

rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

mkdir -p /etc/default/
echo "#  File generated by postfix install.sh" > /etc/default/locale
cp -r /etc/postfix /etc/postfix.template